# Generated by Django 4.0.3 on 2022-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_alter_personmovie_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', through='imdb.PersonMovie', to='imdb.movie'),
        ),
    ]
